version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: provisioning-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: secure_provisioning
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: provisioning-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
